FROM golang:1.20-alpine


WORKDIR /app

COPY go.mod go.sum ./


# Download all dependencies. Dependencies will be cached if the go.mod and go.sum files are not changed
RUN go mod download

COPY . .

RUN go build -o main .

# Expose port 8080 to the outside world
EXPOSE 8080

CMD ["./main"]